# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c14a881db543db5ee77a83c990e47dab"
name = "discounts display pro"
application_url = "https://test.discountsapp.wizardformula.pt"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/shop_redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/app/products_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "discounts/update" ]
  uri = "/webhooks/app/discounts_update"

  [[webhooks.subscriptions]]
  topics = [ "collections/delete" ]
  uri = "/webhooks/app/collections_delete"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/app/products_delete"

  [[webhooks.subscriptions]]
  topics = [ "discounts/delete" ]
  uri = "/webhooks/app/discounts_delete"

  [[webhooks.subscriptions]]
  topics = [ "collections/update" ]
  uri = "/webhooks/app/collections_update"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions_update"

  [[webhooks.subscriptions]]
  topics = [ "discounts/create" ]
  uri = "/webhooks/app/discounts_create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://test.discountsapp.wizardformula.pt/auth/callback",
  "https://test.discountsapp.wizardformula.pt/auth/shopify/callback"
]

[pos]
embedded = false
